name: "dot net test"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: generate markdown
        run: |
          echo "## Test Results" > results.md
          echo "" >> results.md
          echo "### Test Summary" >> results.md
          dotnet test --no-build --verbosity normal | tee -a results.md
      - name: Upload results.md as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.md
